# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tess2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tess2
pod 'TesseractOCRiOS', '4.0.0'
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ENABLE_BITCODE'] = 'NO'
end
end
end